---
- hosts: localhost
  connection: local
  tasks:

    - name: Download latest example templates
      get_url: url=https://s3-us-west-2.amazonaws.com/cloudformation-templates-us-west-2/{{item}} dest={{prefix}}templates/
      with_items: '{{ExampleTemplates}}'

    - name: Document Templates
      cloudformation_autodoc: template={{prefix}}templates/{{item}} dest={{prefix}}templates/{{item}}.md insert={{prefix}}templates/insert.md
      with_items: '{{ExampleTemplates}}'
